apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-hfmt
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr714-0075-0004-tenant/tkrw-pr714-0075-0004-app/devfile-sample-hfmt@sha256:756e1ea072514fd071bae69178ee371770246a22c1e7eff00a9cb3b7ad1cfb41
        name: my-nodejs
        resources: {}
status: {}
